apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: quarkus-ci-triggertemplate-dev
spec:
  params:
    - name: git-repo-url
      description: The git repository url
    - name: git-revision
      description: The git revision
      default: develop
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: quarkus-ci-pipelinerun-dev-
      spec:
        pipelineRef:
          name: quarkus-ci-pipeline
        workspaces:
          - name: shared-workspace
            volumeClaimTemplate:
              spec:
                accessModes:
                  - ReadWriteOnce
                resources:
                  requests:
                    storage: 1Gi
          - name: git-credentials
            secret:
              secretName: git-credentials
        params:
          - name: git-url
            value: $(tt.params.git-repo-url)
          - name: git-revision
            value: $(tt.params.git-revision)
          - name: build-config-name
            value: "eqt-poc-quarkus"
          - name: namespace
            value: "eqt-poc-quarkus-dev"
          - name: values-file
            value: "values-dev.yaml"
          - name: run-analysis
            value: "false"
